AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Bundler/GemFilename:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - signore.gemspec
    - test/**/*

Naming/HeredocDelimiterCase:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Not:
  Enabled: false

Style/StructInheritance:
  Enabled: false
