Metrics/BlockLength:
  Exclude:
    - 'signore.gemspec'
    - 'test/**/*'

Naming/HeredocDelimiterCase:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Not:
  Enabled: false
