AndOr:
  Enabled: false

Documentation:
  Enabled: false

MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

SingleSpaceBeforeFirstArg:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma
