require 'fileutils'
require 'lovely-rufus'
require 'optparse'
require 'ostruct'
require 'psych'
require 'yaml/store'

require_relative 'signore/database'
require_relative 'signore/executable'
require_relative 'signore/signature'
